/**
 * ============================================================
 * PAYROLL CRON JOB — Automatic Month-End Generation
 * ============================================================
 * Runs on the last day of every month at 11:59 PM IST.
 *
 * Logic:
 *   1. Determine current month in YYYY-MM format
 *   2. Call generateAllPayrolls for all active employees
 *   3. Prevent duplicates (handled by service layer)
 *   4. Log results and errors
 *
 * Timezone: Asia/Kolkata
 * ============================================================
 */
const cron = require('node-cron');
const { generateAllPayrolls } = require('../services/payroll.service');

/**
 * Start the cron job. Call this once during server startup.
 */
function startPayrollCron() {
  // ── Schedule: "59 23 28-31 * *" — runs at 23:59 on days 28–31 ──
  // We then check if today is actually the last day of the month.
  // This pattern works for all month lengths (28, 29, 30, 31).
  const job = cron.schedule(
    '59 23 28-31 * *',
    async () => {
      const now = new Date(
        new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' })
      );
      const today = now.getDate();
      const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();

      // Only run on the actual last day of the month
      if (today !== lastDay) return;

      const monthStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
      console.log(`[PAYROLL CRON] Auto-generating payroll for ${monthStr}...`);

      try {
        const results = await generateAllPayrolls(monthStr, {
          notes: 'Auto-generated by month-end cron job',
          generatedBy: null, // System-generated
        });

        console.log(`[PAYROLL CRON] ✅ Done for ${monthStr}`);
        console.log(`  Generated: ${results.generated.length}`);
        console.log(`  Skipped:   ${results.skipped.length}`);
        if (results.errors.length > 0) {
          console.error(`  Errors:    ${results.errors.length}`);
          results.errors.forEach((e) =>
            console.error(`    - ${e.name}: ${e.error}`)
          );
        }
      } catch (err) {
        console.error(`[PAYROLL CRON] ❌ Fatal error for ${monthStr}:`, err.message);
      }
    },
    {
      scheduled: true,
      timezone: 'Asia/Kolkata',
    }
  );

  console.log('[PAYROLL CRON] Month-end auto-generation scheduled (last day, 23:59 IST)');
  return job;
}

module.exports = { startPayrollCron };
